### ISSUE TITLE
app run not working on Windows

### ISSUE THREAD

**Issue by xhanin** [restx/restx#115]
always using column as classpath separator makes app run fail under windows. Should use a platform specific separator.

**Comment by jjbridges** [comment]
I finally got to try the update.  I downloaded 0.34-SNAPSHOT, set my
environment to that, created a new project, pointed it to install
0.34-SNAPSHOT, and said to run the app... and still got "Could not find or
load main class...".

**Comment by xhanin** [comment]
Sorry, the way to test was not the good one: the fix is included in a plugin, not in the shell core itself. So upgrading the shell had no effect. I've done a test on my own using the `0.34-SNAPSHOT` version of `restx-core-shell` plugin, and `app run` is now working.

So I close this issue, it will be generally available with 0.34 release.
