### ISSUE TITLE
restx-samples-hellomongo：404 in  mount-resources  and  mount-sources

### ISSUE THREAD

**Issue by Dreampie** [restx/restx#130]
url：http://192.168.1.111:9080/api/@/ui/api-docs/#/

console log:
```javascript
GET http://192.168.1.111:9080/api/@/api-docs/mount-resources 404 (Not Found)
GET http://192.168.1.111:9080/api/@/api-docs/mount-sources 404 (Not Found)
```

url:http://192.168.1.111:9080/api/@/ui/api-docs/#/operation/city/GET/___cities

```javascript
 GET http://192.168.1.111:9080/api/@/api-docs/notes/hellomongo.rest.CityResource.notes.json 404 (Not Found)
```

**Comment by xhanin** [comment]
The first logs won't show up anymore with 0.34.

The log for the notes.json is "normal": the UI is checking if there are notes available, and a 404 is used to tell that no note is available for that endpoint. We properly handle it in the client, but AFAIK there is no way to prevent the browser from logging that as an error.
