### ISSUE TITLE
Allow @When on module classes and and method annotated with @Provides

### ISSUE THREAD

**Issue by a-peyrard** [restx/restx#150]
Currently @When is used when we use alternatives, it is also allowed on component classes.

First we can add the possibility to use it on modules methods.
We can also add it on module classes directly, it would permit to make all components provided by a module becoming activated on a condition.

The question is what about a module being annotated on its class with a @When and having a method providing a component which is also annotated with @When. I think the more precise need to win, so the method will use the condition of its @When, when the other provided components will use the condition defined at the class level.

**Comment by fcamblor** [comment]
> First we can add the possibility to use it on modules methods.
> We can also add it on module classes directly, it would permit to make all components provided by a module becoming activated on a condition.

Agree

> The question is what about a module being annotated on its class with a @When and having a method providing a component which is also annotated with @When. I think the more precise need to win, so the method will use the condition of its @When, when the other provided components will use the condition defined at the class level.

I'm mitigated about this because the choice we will take (no matter if this the method > class or class > method) is not *obvious* to my POV.
I don't have strong opinion about this though.

My POV would be to just disallow @When if used on a method declared into a @When-ified class : at least it makes things not questionable and allow to put @When globally (class-wide) or specifically (method-wide) but not both.

**Comment by xhanin** [comment]
Very good points Fred, I agree the best is to disallow combining `@When` at module class and method level, I don't see any good use case for that anyway.

**Comment by a-peyrard** [comment]
Agree too, disallowing @When on methods when it has been defined at class
level seems to be the best solution to avoid conflict.

I will prepare a PR for this issue in the near future.

**Comment by a-peyrard** [comment]
I was looking how to bring `@When` in modules, and I thought that I will not create another section in the mustache template, just use the one created for alternatives (https://github.com/restx/restx/blob/master/restx-factory/src/main/resources/restx/factory/processor/ModuleMachine.mustache#L41).

By checking https://github.com/restx/restx/blob/master/restx-factory/src/main/resources/restx/factory/processor/ConditionalMachine.mustache and https://github.com/restx/restx/blob/master/restx-factory/src/main/resources/restx/factory/processor/AlternativeMachine.mustache I think a factorisation of code can be done here too, using the same technique.

The only meaningful difference seems to be the suffix of the name of the FactoryMachine, either "Conditional" or "Alternative". I think it might be a good thing to keep the distinction, but this name could be generated in the processor.

WDYT ?

**Comment by xhanin** [comment]
I agree, factorizing templates is a good option.

**Comment by a-peyrard** [comment]
resolved by #154
