### ISSUE TITLE
Force the registration class for a Component

### ISSUE THREAD

**Issue by a-peyrard** [restx/restx#155]
Currently when defining a class annotated with `@Component` the class used in the `Name` is the component class. So if we want to register it with another class, typically an implemented interface or an inherited class, we have to use a `Module` and a "provides" method.

It might be useful for that kind of cases to have a parameter in the `Component` annotation permitting to force the class. For example something like this : 
```
@Component(asClass = MyInterface.class)
public class MyImplementation implements MyInterface {
```

I totally forgot that I already tried to implement this but didn't finished, I needed this functionality today, and was surprised to not find it in the last snapshot. 
So this a draft https://github.com/a-peyrard/restx/tree/asClass-parameter-for-Component but it just need to take care of Conditional components and to provide some tests and I think I will be able to make a PR with that.

WDYT ?

**Comment by xhanin** [comment]
Sounds good to me!
