### ISSUE TITLE
Improve watch service for windows

### ISSUE THREAD

**Issue by a-peyrard** [restx/restx#161]
In windows, if a file is modified the default watch service is sending three events, one delete, one create and one modify. 
I will try to investigate in order to check if there is a solution for this, otherwise I think that we might solve this by creating a special event coalescor for windows, which will merge delete and create event for same files into a modify event.

**Comment by a-peyrard** [comment]
This problem is happening with IDEA when "safe write" is activated on windows. 

I created a new coalescor `FileWatchEventCoalescor` in order to address this issue:
This coalescor will merge events DELETE and CREATE (if received consecutively), it also
ignores duplicates and ignores MODIFY after a CREATE.
See commit https://github.com/a-peyrard/restx/commit/3f9ab89c67bcd33152961225d7f5b32bd3687f1f
(There is some temporary System.out, it's kind of ugly, and would be removed if I commit this for production).

Currently I did not plug it into WatcherServices, need your opinions first, and I also wanted to benchmark this, but I will need to spend more time on JMH, I just used it to benchmark some basic method so far, I need to find a way to benchmark something like this.

I had to break `FileWatchEvent` immutability though.

So WDYT, should I continue on this way ?

**Comment by xhanin** [comment]
I think the direction is good. About breaking FileWatchEvent immutability, I think I would prefer to keep it and do a copy to change the kind: so the `merge` method would return an `Optional<FileWatchEvent>` which would be the result of the merge, and the caller would replace the previous last event if the merge returns a present `Optional`.

**Comment by a-peyrard** [comment]
At first I wanted to do something like this, but I have a problem with this line: 
https://github.com/a-peyrard/restx/blob/3f9ab89c67bcd33152961225d7f5b32bd3687f1f/restx-common/src/main/java/restx/common/watch/FileWatchEventCoalescor.java#L115
In the `schedulePost` method I keep a reference on the `FileWatchEvent`, so if I do your modification I think that I will not post merged events, but original ones.
(Or I need to encapsulate my events in some `AtomicReference`, pass the reference to the `schedulePost` method and keep references in the queue, but it seams a little bit dirty, isn't it?)

**Comment by xhanin** [comment]
Indeed, I didn't pay attention to that. 

But maybe you could just check if the event is still in the queue before posting it (you could simply begin by `dequeue` it and return a boolean telling if it was removed to do that check). 

It means that you'd need to schedule a post for the merged event and thus it will slightly postpone the actual post. It may even never actually do the post if you always flip between changes in the coalesce period. But I don't think it's that much an issue, we're talking about file system events and such a behavior doesn't make much sense. And I'd really prefer to keep the event immutable, because events are made to be shared and propagated across threads, so immutability is important here IMO.

WDYT?

**Comment by a-peyrard** [comment]
Ok I agree for the immutability part, it might be a good thing to keep it.

For your solution it might be a solution, another one would be based on my last comment, I can do a class like this:
```
static class EventReference {
		private final FileWatchEventKey key;
		Optional<FileWatchEvent> event;

		EventReference(FileWatchEventKey key, FileWatchEvent event) {
			this.key = key;
			this.event = Optional.of(event);
		}

		public void replace(FileWatchEvent newEvent) {
			event = Optional.of(newEvent);
		}

		public void remove() {
			event = Optional.absent();
		}
	}
```
The queue would be a `HashMap<FileWatchEventKey, Deque<EventReference>>` and the `schedulePost`parameter an `EventReference`.
I keep an optional to add a new merge, CREATE + DELETE = void, so in the thread if the reference as an optional absent, it does not post anything in the bus, but still dequeue the reference.

WDYT?

**Comment by xhanin** [comment]
Fine for me, no problem.

**Comment by a-peyrard** [comment]
So I implemented a new solution, using event references. See the corresponding PR: #165.

I also benchmarked the coalescor, to see if the overhead if this new solution was acceptable, so I played a little bit with JMH, you can see this, here: https://github.com/a-peyrard/restx/commit/87384cc2f63e6fbc3d47af3f5147f9220ce3dc0b

And I just noticed something, it seams to be "coalescer" and not "coalescor", maybe I need to add a new commit in the PR to change this ?

Is this implementation ok for you ?

**Comment by xhanin** [comment]
Sounds good!

You're right for coalescer, but I think the rename is out of the scope of this issue. I'm fine with fixing it but it should be done it in a separate issue.
