### ISSUE TITLE
Introduce 'from' parameter in `restx build generate`command

### ISSUE THREAD

**Issue by fcamblor** [restx/restx#172]
It would be nice to improve the `restx build generate <type>` command into something like : `restx build generate <dest_type> [from <src_type>]`

Assuming `from md` would be implicit if not provided.

Thus we would be able to generate every dependencies descriptor types from every dependencies descriptor types.
For instance : `restx build generate md from pom`

It would imply to :
- Provide missing pom/ivy writers from md reader
- Provide missing md writers from pom/ivy readers

**Comment by xhanin** [comment]
Note that we already have the pom/md parsers and the md/pom/ivy writers.

So we are able to convert from pom/md to md/pom/ivy, we just need to support it in the command.

**Comment by fcamblor** [comment]
Closed as migrated to `restx-shell` : https://github.com/restx/restx-shell/issues/1
