### ISSUE TITLE
test generation for POST /

### ISSUE THREAD

**Issue by physikerwelt** [restx/restx#176]
I was trying to generate a test for a methoid that is annotated with `@POST("/")` but I could not that using the web interface

```
java.lang.IllegalArgumentException: unrecognized 'when' format: it must begin with a HTTP declaration of the form 'VERB resource/path'
```

**Comment by fcamblor** [comment]
Could you provided the `yaml` file please ?

**Comment by xhanin** [comment]
So we have a bug when auto capturing the restx spec for endpoints on API root `/`.

**Comment by fcamblor** [comment]
Fixed, thanks for the bug report 👍
