### ISSUE TITLE
Allow to load settings from a file configured through a system property

### ISSUE THREAD

**Issue by xhanin** [restx/restx#186]
Currently when you use `ConfigLoader#fromResource` the behavior is to load settings from classpath resources, one based on provided `env` and a default one.

This behavior requires to either package the settings for each environment in the app, or provide the settings in the classpath of the app server, which is not always very convenient.

It would be nice to be able to provide a specific additional location to look for using a system property. For instance when loading settings with `configLoader.fromResource("myapp/settings")` you could give a location with `-Dmyapp.settings.location=/path/to/my/settings.properties` which would be used to override the settings found in classpath.

**Comment by fcamblor** [comment]
I :+1: the use case where we provide some filesystem path through `-D` props, seems nice to me
