### ISSUE TITLE
`app run` at project root when using srv / ui layout is not properly handled

### ISSUE THREAD

**Issue by xhanin** [restx/restx#188]
It gives an error like this:

```
fgwh-ms-parent> app run
can't find manifest.main.classname property in md.restx.json
alternatively you can provide the class to run with `app run <class.to.Run>`
```

which is not very clear that you need to `cd` to the `srv` directory to do the `app run`

**Comment by xhanin** [comment]
See also #180

**Comment by fcamblor** [comment]
Relates do #97 & #79 in the way we base the `app run` on current `AppSettings`'s sourcesAvailability
