### ISSUE TITLE
Proposal for srv/ui layout improvements

### ISSUE THREAD

**Issue by CedricGatay** [restx/restx#192]
Actually the srv/ui layout is generating a war file containing the ui part in the webapp directory through the use of the war overlay feature.

It might not be the perfect way of doing it (as seen with #180 and related), by discussing at the Hackergarten we were thinking of doing the following : 
- create a third module only enabled with a specific profile to build the full war (very similar to what is done in PR #191, but cleaner)
- change the type of the srv artifact to become an executable jar (to allow launching it easily)

**Comment by fcamblor** [comment]
My POV would be to generate this third (war) module after answering an additionnal question after srv/ui layout generation (in restx shell) : "Do you want to generate a war archive including both srv and ui resources ? Answering no will keep both layers separated. (y/n)"

**Comment by xhanin** [comment]
I like the idea, I think it's cleaner than current layout. Having yet another question to support both options as you suggest Fred is a good idea, but I'm afraid that will introduce additional complexity in tests and maintenance. So I think I'd stick with only 2 options: server only, or srv/ui with either one solution or the other.  You can always make your own adjustments after that if you want. 

So in the end I'm +1 to change the layout with the proposed one, and -0 to have an option to keep both.

**Comment by a-peyrard** [comment]
+1 for the new layout

**Comment by fcamblor** [comment]
Fixed through #191
