### ISSUE TITLE
MongoModule should implement AutoCloseable

### ISSUE THREAD

**Issue by CedricGatay** [restx/restx#193]
Hi there,

I was facing a strange issue with one of our app, let me explain what we're doing and what was causing this : 
 * we run job through quartz
 * these jobs are using injection facilities provided by restx by creating a new factory then closing it when the job is done

When the app was running for quite a long time, we were facing OOME : can not start new native thread from `com.mongodb.Mongo`. By digging into the code I found out that `new MongoClient()` creates a new `Thread` (named MongoCleaner), the problem is that, when we close the factory, the mongoClient is not closed.

The actual fix (for this use case) consists in doing the following when closing the factory : 

    final MongoClient client = factory.getComponent(MongoClient.class);
    if (client != null) {
        client.close();
    }
    factory.close();

Do you think it is a _real_ issue and thus should be fixed by making `MongoModule` implementing / or returning a `AutoCloseable` to do this kind of cleanup ?

**Comment by a-peyrard** [comment]
For me it's a real issue.

I just manage to reproduce the problem (the code is here: https://gist.github.com/a-peyrard/aee7e47f3bc7bd9546a8).

I will try to fix this soon.

(By the way, Xavier or Frederic, I didn't find any module where I would have been able to implement this test, don't we need a module restx-jongo-tests for things like this ?)

**Comment by xhanin** [comment]
Indeed, we need to fix that, thanks for reporting Cedric.

Augustin, good job for the test. I don't know if we need a dedicated module for that, maybe it can just be part of the tests of `restx-jongo`? We use dedicated test modules especially when we need to use the annotation processor of the module under test in the test, but here I think we can do it simpler, unless I miss something?

**Comment by a-peyrard** [comment]
The thing I missed, to be able to implement the test in `restx-jongo`, was the class `MongoEmbedRule` which is defined in `restx-jong-spec-tests`.

**Comment by CedricGatay** [comment]
Thanks for the feedback. I'll see if I can help in solving it.

**Comment by a-peyrard** [comment]
So doing something like this:
```java
    @Provides @Named("close.mongoclient")
    public AutoCloseable closeMongoClient(@Named(MONGO_CLIENT_NAME) final MongoClient client) {
        return new AutoCloseable() {
            @Override
            public void close() throws Exception {
                client.close();
            }
        };
    }

    /*
        this is a hack in order to put the closeMongoClient component in the warehouse
     */
    @Provides
    public AutoPreparable prepareCloseMongoClientComponent(@Named("close.mongoclient") AutoCloseable closeMongoClient) {
        return new AutoPreparable() {
            @Override
            public void prepare() {}
        };
    }
``` 
in MongoModule solves the problem (And also a small modification has to be done in the test, to call `prepare` on the factory). But it looks like a hack to me.

One other solution would be to wrap the `MongoClient`.
I will continue to investigate a little bit later, I'm watching one of the two games of the year (and probably the hold-up of the century, if the score stay like this:)).

**Comment by CedricGatay** [comment]
Does the prepare step is properly called when we create the factory "manually". In my use case I create the factory using the following code

            instance = Factory.builder().addFromServiceLoader().build();

I think this is doing the right thing with the call to prepare, but as you're telling the test needs to be adjusted, I'm wondering...

Off topic : nice game tonight ;)

**Comment by a-peyrard** [comment]
Neither the `prepare` method, nor the `start` method are called when a `Factory` is manually built. They have to be called manually.
