### ISSUE TITLE
Issue with query param using Optional of java on class other than String

### ISSUE THREAD

**Issue by driccio** [restx/restx#214]
Hi Restx team,

Using Optional of java with other type than String seems to be not supported on endpoint mapping.

```
import java.util.Optional;

@GET("/all")
public Iterable<Object> all(Optional<Integer> param) {
...
}
```

It causes the following exception :
`java: no suitable method found for convert(java.util.Optional<java.lang.String>,java.lang.Class<java.lang.Integer>)`

For everyone who get this issue. You can 'by-pass' this issue with these 2 temporary solutions :
- Use Optional of guava
- Use Optional<String> (of java) and parse Integer manually...

Damien

**Comment by fcamblor** [comment]
If you can, it would be nice to try to build branch `better-query-params` of https://github.com/fcamblor/restx/ (which represents current status for #117)

If this solves your problem, it's ok. 
Otherwise, it may be worth adding this case in #146

**Comment by driccio** [comment]
Hi Fred,

I tried with a build from better-query-params and it works perfectly.

**Comment by fcamblor** [comment]
Cool, closing the issue as it may be resolved in the future when we'll merge `better-query-params` PR :-)
