### ISSUE TITLE
Mark private methods in ResourceRoute as protected

### ISSUE THREAD

**Issue by Tomsons** [restx/restx#215]
Is it possible to mark private methods as protected within the `restx.ResourceRoute` class. This class has some nice helper methods such as `notFound` which could be really helpful when overriding the `handle` method.

Thank you
Thomas

**Comment by xhanin** [comment]
Sure, submit a pull request and we will accept it, no problem.

On Tue, Sep 15, 2015 at 5:42 PM, Tomsons <notifications@github.com> wrote:

> Is it possible to mark private methods as protected within the
> restx.ResourceRoute class. This class has some nice helper methods such
> as notFound which could be really helpful when overriding the handle
> method.
>
> Thank you
> Thomas
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/restx/restx/issues/215>.
>



-- 
Xavier Hanin
Lead architect at 4SH France - http://www.4sh.fr/
RESTX creator and lead developer - http://restx.io/
BordeauxJUG creator - http://www.bordeauxjug.org/
Apache Ivy Creator - http://ant.apache.org/ivy/

**Comment by fcamblor** [comment]
Closed through #217
