### ISSUE TITLE
Avoiding to list every available endpoints when on PROD mode

### ISSUE THREAD

**Issue by fcamblor** [restx/restx#234]
Currently, if you go on an unknown restx API path (http://yourdomain/api/blah for instance), you get the listing of every available routes, which may gives hints to an attacker.

It is useful in DEV mode, however I think this behaviour should be disabled in PROD.

This was discussed [on a ggroup thread](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/restx/PYBsEtLN1mE/dh0wdIWK_uYJ) and I think providing the feature "out of the box" (instead of having to code our own filter everytime) would be better.

**Comment by a-peyrard** [comment]
+1 for this, I thought it was already only in dev mode :)

**Comment by a-peyrard** [comment]
This issue has been addressed in 0.33.2, 0.34.1 and current snapshot version.
see : https://github.com/restx/restx/commit/fe0e5998333cd4cbc78f57f520a26d4732908006
