### ISSUE TITLE
md.restx.json

### ISSUE THREAD

**Issue by ferronrsmith** [restx/restx#247]
is there a way to add repositories to this json file ?
It gets overwritten if I try adding it to the pom.xml

**Comment by fcamblor** [comment]
I don't understand, can you elaborate ?

**Comment by ferronrsmith** [comment]
I wanted to include a custom repository inside the generated pom, because currently the file gets overwritten every time regenerate the pom/ivy files. Think I figured it out. I'll use a fragment

**Comment by ferronrsmith** [comment]
Thanks
