### ISSUE TITLE
jrebel

### ISSUE THREAD

**Issue by ferronrsmith** [restx/restx#249]
is there anyway to configure jrebel to run with restx ?

**Comment by fcamblor** [comment]
I never tried since restx already provides hot compile/reload out of the box.
Which jrebel feature would you need ?

**Comment by ferronrsmith** [comment]
i wanted to be able to debug my code. I didn't see anything in the docs on debugging.

**Comment by fcamblor** [comment]
This is a standard java application, so you can debug all the way you debug a standard application
IDE configuration documentation may be found [here](http://restx.io/docs/ide.html)
