### ISSUE TITLE
Download a file

### ISSUE THREAD

**Issue by echaouchna** [restx/restx#251]
Hi,

is there a way to send a file from a restx web service

Thanks

**Comment by fcamblor** [comment]
Hi Nabil,

Just to be sure, can you elaborate a bit more ?

Do you want to upload a file to a restx endpoint ?
Or do you want to download a file from a restx endpoint ?

Regards,

Frédéric Camblor  <http://fcamblor.wordpress.com/>
<http://www.twitter.com/fcamblor>
BDX.io <http://bdx.io> Leader
Restx <http://restx.io/> commiter
Jenkins <http://jenkins-ci.org/> community member & plugin commiter

**Comment by echaouchna** [comment]
I want to download a file from a restx endpoint.

I've tried to change the content type of the response using the @Produces("application/octet-stream") annotation, but when I run the application, I get this error: 

This may be because the content type 'application/octet-stream' is not handled by your RESTX install.

Possible causes:
  - you set the content type manually and mistyped it
  - you are missing the EntityResponseWriterFactory for this content type in your classpath

I am using restx 0.34.1

**Comment by fcamblor** [comment]
Ok, I would suggest to have a look at [ResourcesRoute](https://github.com/restx/restx/blob/master/restx-core/src/main/java/restx/ResourcesRoute.java) class allowing to serve some file from your classpath.

A usage of such route definition may be found, for instance, in [WebJarsModule](https://github.com/restx/restx/blob/master/restx-webjars/src/main/java/restx/webjars/WebJarsModule.java).
This specific example implies that :
- We will have a route which will serve `/@/webjars/[path/to/file]` urls
- `ResourcesRoute` will look for `classpath:META-INF/resources/webjars/[path/to/file]` resource (in classpath) and serve it automatically

If you don't want to serve your file from classpath, you can subclass `ResourcesRoute` and override `handle(RestxRequestMatch, RestxRequest, RestxResponse, RestxContext)` method which will give you the `RestxResponse` where you will be able to write your content.
An example can be found [here](https://github.com/fcamblor/restx-multipart/blob/master/README.md#bonus--downloading-file-sample)

**Comment by echaouchna** [comment]
Thank you, I've been able to subclass ResourcesRoute and used it to download files, I still have some questions though:

- Can I use path variables in the baseRestPath, for example use /user/{id}/report ?
- Is there a way to read and validate query params, I know it is possible to use getQueryParams but I think it's not as convenient as using annotations ?

**Comment by fcamblor** [comment]
> Can I use path variables in the baseRestPath, for example use /user/{id}/report ?

I guess you can, simply by using the `RestxRequestMatch.match.getPathParam()` in your `handle()` method.
Just give it a try to see if it works :-)

> Is there a way to read and validate query params, I know it is possible to use getQueryParams but I think it's not as convenient as using annotations ?

There isn't any better way currently on 0.34.1.

Anyway, in next restx release, #177 should be fixed and you should be able to :
- Use complex types (that is to say, other types than raw Strings like DateTime, BigDecimal and so on...) 
- Embed QUERY parameters into POJOs, and use bean validation on those POJO to validate those query parameters (may be useful when defining POJOs like Criteria)

**Comment by echaouchna** [comment]
Ok it works, but the created endpoint does not appear on the API docs interface.

One last question, is there a way to limit access to the created resource to some roles ?

Thanks :-)

**Comment by fcamblor** [comment]
Creating manually a `Route` offers low level API (like giving access to `RestxResponse`), however, you will have to handle things programmatically (not through annotation).

What I would suggest is create a `@Resource` component with what you would want (typically, an endpoint with `@GET` and `@RolesAllowed` on it) and look at the generated router class (typically, if you create a `FooResource` class, a `FooResourceRouter` will be generated through annotation processing inside your `target/generated-sources/` folder)

Look at this `FooResourceRouter` and you will see the good way to implement :
- Security
- API Doc
.. on your route :-)

(this is a general answer : preferring to teach you fishing than giving you a fish ;-))

**Comment by echaouchna** [comment]
Good tip :-) now I'm able to check roles.

Thank you
