### ISSUE TITLE
Improve circular dependency exception message

### ISSUE THREAD

**Issue by Mathieu-Castets** [restx/restx#252]
I had a case of circular dependency (constructor injection) but it was quite hard to figure it out. Indeed, RESTX server couldn't start and the Exception wasn't clear enough:

> WARN  / - unavailable
> java.lang.IllegalStateException: problem with dependency resolution order BillOfMaterials{[QueryByClass{componentClass=restx.RestxFilter[AppClassLoader]}, QueryByClass{componentClass=restx.RestxRouteFilter[AppClassLoader]}, QueryByClass{componentClass=restx.RestxRouter[AppClassLoader]}, QueryByClass{componentClass=restx.RestxRoute[AppClassLoader]}]} for Name{name='RestxRouting', clazz=restx.RestxRouting[AppClassLoader]} not yet satisfied
>   at restx.factory.Factory.buildAndStore(Factory.java:1202)
>   at restx.factory.Factory.buildAndStore(Factory.java:1071)
>   at restx.factory.Factory.access$600(Factory.java:37)
>   at restx.factory.Factory$NameQuery.doFindOne(Factory.java:604)
>   at restx.factory.Factory$SingleQuery.doFind(Factory.java:521)
>   at restx.factory.Factory$Query.find(Factory.java:448)
>   at restx.factory.Factory$ClassQuery.doFind(Factory.java:662)
>   at restx.factory.Factory$MultipleQuery.doFindOne(Factory.java:486)
>   at restx.factory.Factory$Query.findOne(Factory.java:437)
>   at restx.factory.Factory$Query.findOneAsComponent(Factory.java:440)
>   at restx.factory.Factory.getComponent(Factory.java:798)
>   at restx.RestxMainRouterFactory.newStdRouter(RestxMainRouterFactory.java:544)
>   at restx.RestxMainRouterFactory.build(RestxMainRouterFactory.java:375)
>   at restx.RestxMainRouterFactory.newInstance(RestxMainRouterFactory.java:70)
>   at restx.servlet.RestxMainRouterServlet.init(RestxMainRouterServlet.java:74)
>   at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:519)
>   at org.eclipse.jetty.servlet.ServletHolder.doStart(ServletHolder.java:331)
>   at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
>   at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:747)
>   at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:265)
>   at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1250)
>   at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:706)
>   at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:492)
>   at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
>   at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229)
>   at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
>   at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229)
>   at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
>   at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
>   at org.eclipse.jetty.server.Server.doStart(Server.java:277)
>   at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
>   at restx.server.JettyWebServer.start(JettyWebServer.java:109)
>   at restx.server.JettyWebServer.startAndAwait(JettyWebServer.java:114)
>   at my.package.project.AppServer.main(AppServer.java:17)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:498)
>   at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by xhanin** [comment]
Indeed, the exception could make it clear when you have a circular dependency.
