### ISSUE TITLE
Unable to install shell, version 0.34.1 - wrong sha-1  on javassist

### ISSUE THREAD

**Issue by riccardocossu** [restx/restx#256]
I have just installed latest restx version (never used it before), but 'shell install' fails with this message:

:: problems summary ::
:::: WARNINGS
        [FAILED     ] org.javassist#javassist;3.16.1-GA!javassist.jar: invalid sha1: expected=315891b371395271977af518d4db5cee1a0bc9bf computed=b5556188bcba9b420bff5f066905972f3851efd8 (240ms)

        [FAILED     ] org.javassist#javassist;3.16.1-GA!javassist.jar:  (0ms)

I double checked and the sha-1 seems right...

**Comment by fcamblor** [comment]
Hi,

mmmm .. that's weird, I'm facing the exact same issue as yours, as if repo1.maven.org had an incompatible jar/sha1 pair (even though their modification date is from 2012)

Never faced this before, so I investigated with a local cached javassist jar I had in my local ivy repository, and that time, `shasum` of the jar gives me `315891b371395271977af518d4db5cee1a0bc9bf` (eg, the expected one)

=> Seems like the jar on maven repo has been altered in some manner.
You can find a non-altered jar [on ibibio](http://maven.ibiblio.org/maven2/org/javassist/javassist/3.16.1-GA/javassist-3.16.1-GA.jar) (download the file and copy it on `~/.ivy2/cache/org.javassist/javassist/jars/javassist-3.16.1-GA.jar` and it should be OK, I guess...

Will raise an issue to maven folks with this.

**Comment by fcamblor** [comment]
FYI, raised https://issues.sonatype.org/browse/MVNCENTRAL-1533

**Comment by fcamblor** [comment]
`MVNCENTRAL-1533` has just been resolved, new artefact should be propagated across maven central at worst in ~2h

@riccardocossu If you can try again after this delay, it would be very nice :-)

**Comment by fcamblor** [comment]
Seems like javassist update has been propagated to maven central.

Be sure to remove your ivy cache prior to trying `restx shell install` again :
`rm -Rf ~/.ivy2/cache/org.javassist/javassist/`

**Comment by fcamblor** [comment]
BTW thanks for spotting it 👍

**Comment by riccardocossu** [comment]
worked for me as well, thanks for you prompt help!
(I had no need to clean ivy cache anyway, FYI)
