### ISSUE TITLE
Outdated example about errors management in docs

### ISSUE THREAD

**Issue by Mathieu-Castets** [restx/restx#258]
Currently, there is an [outdated example in the documentation page ](http://restx.io/docs/ref-errors-management.html). Looking at the Raising Errors paragraph:

    if (!companyResource.findCompanyByKey(user.getCompanyRef()).isPresent()) {
          throw RestxError.on(User.Rules.ValidCompanyRef.class)

However, RestxError doesn't provide any `on` static method. 

Correct version should rather be:

    if (!companyResource.findCompanyByKey(user.getCompanyRef()).isPresent()) {
        throw restxErrors.on(User.Rules.ValidCompanyRef.class)

`restxErrors` being the variable name of the *injected* `RestxErrors` component.

**Comment by nhumblot** [comment]
A pull request on this subject has been submitted. Waiting for validation or comments on it.

https://github.com/restx/restx.github.io/pull/14

**Comment by fcamblor** [comment]
@nhumblot's PR has just been merged, closing the issue.
