### ISSUE TITLE
Extract restx shell from restx distribution

### ISSUE THREAD

**Issue by fcamblor** [restx/restx#275]
In my opinion, restx-shell and restx distribution should have different lifecycles, even if we have a dependency between restx-shell artefacts and `restx-factory` (and transitively on `restx-common`), which are not changing very often.

![image](https://user-images.githubusercontent.com/603815/29769981-fbd4da98-8bec-11e7-9292-e8828a8cb4dd.png)

=> I would make 2 separate projects which would allow us to make releases of the shell independently from the restx distribution.

This extraction would concern modules `restx-package`, `restx-shell-manager`, `restx-shell`, `restx-build`
\+ shell plugins :`restx-core-shell`, `restx-specs-shell` and `restx-build-shell`

We would keep artefact coordinates as is, but would release it into 2 different releases processes.

WDYT ?

**Comment by xhanin** [comment]
Sounds good indeed. +1 for me

On Mon, Aug 28, 2017 at 12:39 PM, Frédéric Camblor <notifications@github.com
