### ISSUE TITLE
Session cookie values incompatible with Jetty9 and RFC6265

### ISSUE THREAD

**Issue by xhanin** [restx/restx#284]
When running restx in jetty 9, trying to open a session raises an exception:
```
java.lang.IllegalArgumentException: RFC6265 Cookie values may not contain character: ["]
	at org.eclipse.jetty.http.Syntax.requireValidRFC6265CookieValue(Syntax.java:136) ~[na:na]
	at org.eclipse.jetty.server.Response.addSetRFC6265Cookie(Response.java:269) ~[jetty-server-8.1.8.v20121106.jar:9.4.7.v20170914]
	at org.eclipse.jetty.server.Response.addCookie(Response.java:231) ~[jetty-server-8.1.8.v20121106.jar:9.4.7.v20170914]
	at restx.servlet.HttpServletRestxResponse.addCookie(HttpServletRestxResponse.java:86) ~[restx-servlet-0.36-beta1-4sh.jar:na]
	at restx.security.RestxSessionCookieFilter.updateSessionInClient(RestxSessionCookieFilter.java:163) ~[restx-core-0.36-beta1-4sh.jar:na]
```

**Comment by fcamblor** [comment]
What would then be the idea here ? base64 encoding/decoding of `RestxSession` cookie ?

**Comment by xhanin** [comment]
Yes, I think that would be the safest option. It's a backward incompatible change at client level (if one uses the cookie value), so we should still support unencoded values based on a setting.

**Comment by pcata6** [comment]
We have an equivalent type of issue in tomcat 9:

```
java.lang.IllegalArgumentException: An invalid character [34] was present in the Cookie value
	at org.apache.tomcat.util.http.Rfc6265CookieProcessor.validateCookieValue(Rfc6265CookieProcessor.java:182) ~[tomcat-coyote.jar:9.0.4]
	at org.apache.tomcat.util.http.Rfc6265CookieProcessor.generateHeader(Rfc6265CookieProcessor.java:115) ~[tomcat-coyote.jar:9.0.4]
	at org.apache.catalina.connector.Response.generateCookieString(Response.java:1010) ~[catalina.jar:9.0.4]
	at org.apache.catalina.connector.Response.addCookie(Response.java:962) ~[catalina.jar:9.0.4]
	at org.apache.catalina.connector.ResponseFacade.addCookie(ResponseFacade.java:385) ~[catalina.jar:9.0.4]
	at restx.servlet.HttpServletRestxResponse.addCookie(HttpServletRestxResponse.java:73) ~[restx-servlet-0.34.jar:na]
	at restx.security.RestxSessionCookieFilter.updateSessionInClient(RestxSessionCookieFilter.java:159) ~[restx-core-0.34.jar:na]
	at restx.security.RestxSessionCookieFilter.access$000(RestxSessionCookieFilter.java:42) ~[restx-core-0.34.jar:na]
```
Temporarly we can use this configuration added in context.xml

`<CookieProcessor className="org.apache.tomcat.util.http.LegacyCookieProcessor" />`

**Comment by fcamblor** [comment]
bse64 encoding or `RestxSession` cookie won't work as, sometimes, base64 encoding appends 1 or 2 `=` signs at the end of the base64-encoded string

AND

Some `HttpServletResponse` implementations are escaping cookies values with double quotes when an `=` sign is found in the value (example implementation : the one in jetty8 [here](https://eclipse.googlesource.com/jetty/org.eclipse.jetty.project/+/jetty-8.1.19.v20160209/jetty-http/src/main/java/org/eclipse/jetty/http/HttpFields.java#983) then [there](https://eclipse.googlesource.com/jetty/org.eclipse.jetty.project/+/jetty-8.1.19.v20160209/jetty-util/src/main/java/org/eclipse/jetty/util/QuotedStringTokenizer.java#396))

[Base58check](https://stackoverflow.com/a/18949941/476345) may be another option

**Comment by pcata6** [comment]
I agree, Base58 should be a good solution to solve this issue.

**Comment by fcamblor** [comment]
Considering [`com.chrylis:base58-codec` library](https://github.com/chrylis/base58-codec/)

My only concern with this lib is it pulls `commons-lang3` transitive dep for nearly nothing .. [proposed a PR to fix this](https://github.com/chrylis/base58-codec/pulls)

**Comment by fcamblor** [comment]
Released a forked version of base58-codec under the restx umbrella yesterday.
It'a basically the same version than latest 1.2.0, except that `commons-lang3` dependency has been removed (there is basically no transitive dependency pulled from the lib)

http://repo1.maven.org/maven2/io/restx/restx-base58-codec/1.2.1/

PR #296 is based on this artefact

**Comment by Infiniverse** [comment]
This problem has existed for many version, and we've been working around it. Wireshark shows that a typical session cookie looks like:

Cookie: RestxSession-truedb="{\"_expires\":\"2019-02-19T08:42:44.993Z\",\"principal\":\"superuser\",\"sessionKey\":\"5891338c-faef-4e0e-b193-8f51f2b5bffd\"}"; RestxSessionSignature-truedb="Y+CSfnBPPqJPMjo567dg7scAcIg="

This totally borked. The RFC doesn't allow for quotes, and it looks like REST-X is trying to escape them which is doubly broken.

Why don't you just remove the quotes - it doesn't look like any of the values ever return a quote or a comma, so you can still parse by splitting the comma.

**Comment by fcamblor** [comment]
To be 100% accurate, when I look into my cookies, I see something like 
```
RestxSession="{\"_expires\":\"2019-02-16T19:19:20.922+01:00\",\"principal\":\"XXX\",\"sessionKey\":\"aaaaaa123-aa12-1234-a1a2-a1b2c3d4e5f6\"}"; RestxSessionSignature="xxxxxxxxxxxxxxxxxxxxxxxxxxx="
```

> The RFC doesn't allow for quotes

Yes that's the point of this issue.
Honestly, I was not aware about this constraint before @xhanin raised it.
Other (old) Java application servers (such as Tomcat 6/7 or jetty 8) were not complaining about it ... now it is something they are enforcing in newer versions.

> Why don't you just remove the quotes - it doesn't look like any of the values ever return a quote or a comma, so you can still parse by splitting on the comma.

Multiple reasons we cannot remove the quotes :
- As you may notice, we rely on JSON to serialize/parse the `RestxSession` entry. Implementing our own parser/reader would not really serve the purpose of having something simple here.
- We may thing about putting quotes in `principal` value (yes, that would be weird, but nothing prevents it)
- It is possible to customize what is stored into the `RestxSession` entry by providing additionnal `RestxSession.Definition.Entry` components. And here, we won't have any control on how restx users used this feature (I cannot tell you that nobody is using double quotes into his specific session entries)

That's why using the Base58 path is the better for me.

FYI, with PR #296, I get following cookies which are RFC 6265 compliant :
```
RestxSession=3BheaD3kq6VSp11mj53TsJ9BtBegMNEq5Zri73ShdpYW5zhB3baJB3ETP9aSV5YTxzxNwkM3tQ4pKy1qnSKBYL6ehcLAkYNXphdHcw5BkAYqHgmnL9xQouWSL2MyeTWq5PV4uynWrWUeDpFXdxhxHya9pPYFypg; RestxSessionSignature=MswsCTe3prAFvoSn57oGrTfV4xjq8YcQXvU4La
```

**Comment by Infiniverse** [comment]
Ok, all good thoughts. (btw, we first reported the cookie problem on the google forum back in 2015: https://groups.google.com/forum/#!topic/restx/axKeTNnQJak ).

I've tested #296 here and it works fine. Is there any chance we could get a 0.35.2 release quickly? As things stand 0.35.1 is totally broken with any modern http client that processes cookies properly.

**Comment by fcamblor** [comment]
Wow completely missed this 2015 discussion :-)

I'd prefer to push this change in an upcoming 0.36.
We're almost ready, I'm only tracking a jongo incompatibility (#285) I'd like to tackle prior to releasing it.

**Comment by Infiniverse** [comment]
Ok - looking forward to a release :), in meantime I'm using a local snapshot of #285 - we've been stuck for a couple of days with this cookie problem as we're updating our codebase to the latest and greatest and this bug hit us hard.

**Comment by Infiniverse** [comment]
Hey, it's been almost a month - any news on when this might be released?

**Comment by pobk** [comment]
@fcamblor Are you any further with with this?
