### ISSUE TITLE
Implementing a continuous integration

### ISSUE THREAD

**Issue by nhumblot** [restx/restx#322]
Having a continuous integration could help the maintainers of the project and improve stability.

Ideally, the continuous integration has to be trigged for every pull request and every push on master.

Integration should be tested for java supported LTS and last version, meaning java 8, 11 and 14.

restx seems to have a passive with TravisCI given the `.travis.yml` file at the root of the project. [Travis CI looks to be completely free for open source projects with very comfortable characteristics](https://travis-ci.com/plans). Competitor [Circle CI offers a lot of free credits](https://circleci.com/open-source/) (more than what restx needs) for open source projects.

Travis CI looks to be the better option on paper, we could start by performing a `mvn verify` for jdk8 and jdk11, then extends it on the last jdk version when jdk11 compatibility will pass.

Are you ok with this proposition @xhanin & @fcamblor ? Feel free to share your opinion and what you would like to have if you don't agree.

I can work on the yaml file describing the CI behaviour on my side but you will have to register the restx project on the CI provider to make it work as I do not have the rights to do it.

**Comment by xhanin** [comment]
That sounds perfect!

**Comment by nhumblot** [comment]
Hi @xhanin 

I have an [integration](https://github.com/nhumblot/restx/commits/322_ci_test_jdk8_jdk11) ready for a review. [It looks like restx is not active on Travis CI for the moment](https://travis-ci.org/github/restx/restx). Could you please enable it ? I will submit a pull request after that.

Thank you for your help.

**Comment by xhanin** [comment]
Hi @nhumblot 

I've activated the repository on travis. I've also invited you to the restx team, you may need an access to setup the CI, and I'm confident you will use your access with care :)
