### ISSUE TITLE
Is there a getHeaders() method?

### ISSUE THREAD

**Issue by jseparovic** [restx/restx#348]
I can see that I'm able to getHeader(String), but I want to collect all `x-*` headers without knowing them in advance.

I'm able to use `req.unwrap(Request.class)` to get the text request headers and parse. 

Just thought it would be nicer to have a getHeaders on the `RestxRequest` class.

**Comment by xhanin** [comment]
indeed, that sounds like a good addition to the API.
there is not much activity on restx recently, but feel free to submit a PR for that

**Comment by fhebuterne** [comment]
Hi, this is available in restx version 1.1.0
